services:
  app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/opt/app
    command: bash -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    depends_on:
      rabbit:
        condition: service_healthy

  rabbit:
    image: rabbitmq:4.0.2-management
    restart: always
    ports:
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - .env

