services:
  app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/opt/app
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head; uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
