"""Added PortfolioV01 Table

Revision ID: 9b4e6e051bc3
Revises: 
Create Date: 2024-10-22 14:54:34.707696

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b4e6e051bc3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfoliov01",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("num", sa.Integer(), nullable=False),
        sa.Column("dl", sa.Text(), nullable=False),
        sa.Column("pl", sa.Text(), nullable=False),
        sa.Column("kontragent", sa.Text(), nullable=False),
        sa.Column("dltype", sa.CHAR(length=1), nullable=False),
        sa.Column("dlnum", sa.Text(), nullable=False),
        sa.Column("dldate", sa.DATE(), nullable=False),
        sa.Column("plquan", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("sumavans", sa.Integer(), nullable=False),
        sa.Column("sumlp", sa.Integer(), nullable=False),
        sa.Column("sumvp", sa.Integer(), nullable=False),
        sa.Column("sumdl", sa.Integer(), nullable=False),
        sa.Column("suminv", sa.Integer(), nullable=False),
        sa.Column("valos", sa.Integer(), nullable=False),
        sa.Column("sumos", sa.Integer(), nullable=False),
        sa.Column("fpay", sa.Integer(), nullable=False),
        sa.Column("opay", sa.Integer(), nullable=False),
        sa.Column("statdate", sa.DATE(), nullable=False),
        sa.Column("admdate", sa.DATE(), nullable=False),
        sa.Column("admavdldate", sa.DATE(), nullable=False),
        sa.Column("supp", sa.Text(), nullable=False),
        sa.Column("catavto", sa.CHAR(length=1), nullable=False),
        sa.Column("comtr", sa.CHAR(length=3), nullable=False),
        sa.Column("div", sa.Text(), nullable=False),
        sa.Column("men", sa.Text(), nullable=False),
        sa.Column("brand", sa.Text(), nullable=False),
        sa.Column("mod", sa.Text(), nullable=False),
        sa.Column("mar", sa.Integer(), nullable=False),
        sa.Column("bid", sa.Integer(), nullable=False),
        sa.Column("lp", sa.Text(), nullable=False),
        sa.Column("term", sa.Integer(), nullable=False),
        sa.Column("aff", sa.Text(), nullable=False),
        sa.Column("ist", sa.Text(), nullable=False),
        sa.Column("secl", sa.CHAR(length=3), nullable=False),
        sa.Column("addtype", sa.Text(), nullable=False),
        sa.Column("exdate", sa.DATE(), nullable=False),
        sa.Column("rep", sa.CHAR(length=3), nullable=False),
        sa.Column("purp", sa.Text(), nullable=False),
        sa.Column("val", sa.Integer(), nullable=False),
        sa.Column("addinc", sa.Integer(), nullable=False),
        sa.Column("avans", sa.Integer(), nullable=False),
        sa.Column("bonus", sa.Integer(), nullable=False),
        sa.Column("agsum", sa.Integer(), nullable=False),
        sa.Column("dua", sa.Text(), nullable=False),
        sa.Column("dup", sa.Text(), nullable=False),
        sa.Column("duz", sa.Text(), nullable=False),
        sa.Column("duc", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("insert_date", sa.DATE(), nullable=False),
        sa.Column("insert_file", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("portfoliov01")
    # ### end Alembic commands ###
